name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight
  workflow_dispatch: # Allow manual run

jobs:
  generate:
    name: Generate Snake Animation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Generate the snake game
        uses: Platane/snk@v2
        with:
          github_user_name: <your-github-username> # Replace with your GitHub username
          outputs: dist/snake.svg

      - name: Push the snake animation to the output branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
